[profile.default]
solc_version = "0.8.19"
optimizer = true
optimizer_runs = 200
src = "src"
test = "test"
libs = ["lib"]
remappings = ["@openzeppelin/=lib/openzeppelin-contracts/","forge-std/=lib/forge-std/src/"]

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }


